/*
 * nokia_gfx full graphics set
 * auto-generated by xbmtool.sh
 */
#ifndef NOKIA_GFX_H
#define NOKIA_GFX_H
#include <stdint.h>


/* full frame for nokia_splash.xbm */
extern const uint8_t nokia_gfx_nokia_splash[];


#endif
