/*
 * ssd1306_gfx full graphics set
 * auto-generated by xbmtool.sh
 */
#ifndef SSD1306_GFX_H
#define SSD1306_GFX_H
#include <stdint.h>


/* full frame for ssd1306_splash.xbm */
extern const uint8_t ssd1306_gfx_ssd1306_splash[];


#endif
